// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAifNHPcwJk1MFkfXRxWoEMd8FUtDqqQU',
    appId: '1:158550708125:web:f27cf379e56aa4972da974',
    messagingSenderId: '158550708125',
    projectId: 'gluten-free-scanner-e95e8',
    authDomain: 'gluten-free-scanner-e95e8.firebaseapp.com',
    databaseURL: 'https://gluten-free-scanner-e95e8-default-rtdb.firebaseio.com',
    storageBucket: 'gluten-free-scanner-e95e8.appspot.com',
    measurementId: 'G-ENCGMLYMC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-B4676yhrxk9wnguu8LXAeCb9h-wDNgo',
    appId: '1:158550708125:android:76d236138161e5d72da974',
    messagingSenderId: '158550708125',
    projectId: 'gluten-free-scanner-e95e8',
    databaseURL: 'https://gluten-free-scanner-e95e8-default-rtdb.firebaseio.com',
    storageBucket: 'gluten-free-scanner-e95e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABKDvHqBA_KMTJ4u0l1Sz9OreZOkK9WdM',
    appId: '1:158550708125:ios:e06f6934280775542da974',
    messagingSenderId: '158550708125',
    projectId: 'gluten-free-scanner-e95e8',
    databaseURL: 'https://gluten-free-scanner-e95e8-default-rtdb.firebaseio.com',
    storageBucket: 'gluten-free-scanner-e95e8.appspot.com',
    iosClientId: '158550708125-hlvaolmlh4gnj68cgkijcrnnbjmq0ui6.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABKDvHqBA_KMTJ4u0l1Sz9OreZOkK9WdM',
    appId: '1:158550708125:ios:e06f6934280775542da974',
    messagingSenderId: '158550708125',
    projectId: 'gluten-free-scanner-e95e8',
    databaseURL: 'https://gluten-free-scanner-e95e8-default-rtdb.firebaseio.com',
    storageBucket: 'gluten-free-scanner-e95e8.appspot.com',
    iosClientId: '158550708125-hlvaolmlh4gnj68cgkijcrnnbjmq0ui6.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
